/* automatically generated by rust-bindgen 0.66.1 */

pub type max_align_t = f64;
pub const Rboolean_FALSE: Rboolean = 0;
pub const Rboolean_TRUE: Rboolean = 1;
pub type Rboolean = ::std::os::raw::c_int;
