/* automatically generated by rust-bindgen 0.66.1 */

extern "C" {
    pub static mut R_num_math_threads: ::std::os::raw::c_int;
}
extern "C" {
    pub static mut R_max_num_math_threads: ::std::os::raw::c_int;
}
